version: '3'
services:
  api-gateway:
    build: 
      dockerfile: Dockerfile
      context: ./api-gateway
    ports:
      - '3001:3001'
    depends_on:
      - db
      - "kafka"
    networks:
      - fena-network

  email-microservice:
    build: 
      dockerfile: Dockerfile
      context: ./email
    depends_on:
      - db
      - "kafka"
    networks:
      - fena-network

  db:
    build: 
      dockerfile: Dockerfile
      context: ./mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=fena
      - MYSQL_USER=balen
      - MYSQL_PASSWORD=fenabalen
    ports:
      - '3306:3306'
    networks:
      - fena-network
    restart: always

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
    networks:
      - fena-network

  kafka:
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    networks:
      - fena-network

networks:
  fena-network:
    driver: bridge
